title: CRG Biocore PHINDaccess RNA-seq course 2020
description: Some description
url: "https://biocorecrg.github.io/PHINDaccess_RNAseq_2020" 

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

sass:
  sass_dir: _sass
  style: compressed
